# Generated by Django 5.1.1 on 2024-10-27 09:09

import django.core.validators
import regular_exam.author_app.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('author_app', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='author',
            name='first_name',
            field=models.CharField(max_length=40, validators=[django.core.validators.MinLengthValidator(4), regular_exam.author_app.validators.LettersOnlyValidator()]),
        ),
        migrations.AlterField(
            model_name='author',
            name='passcode',
            field=models.CharField(help_text='Your passcode must be a combination of 6 digits', validators=[regular_exam.author_app.validators.PasscodeValidator()]),
        ),
    ]
