# Generated by Django 5.1.1 on 2024-10-27 12:27

import django.core.validators
import regular_exam.author_app.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('author_app', '0003_author_last_name'),
    ]

    operations = [
        migrations.AlterField(
            model_name='author',
            name='last_name',
            field=models.CharField(max_length=50, validators=[django.core.validators.MinLengthValidator(2), regular_exam.author_app.validators.LettersOnlyValidator()]),
        ),
    ]
